### PR TITLE
Add support for executing subsets of tests via CLI

### PR DESCRIPTION
**Pull request by CraigFe**
This is a candidate solution for #156.

CC: @samoht

### CODE REVIEW

**Comment by CraigFe** [comment]
This behaviour probably warrants some unit testing.

Happy to do that in either this PR or another. Since there are currently no unit tests at all, it didn't feel like it belonged here.

**Comment by samoht** [comment]
That looks great! Can you add some documentation and a few tests?

**Comment by CraigFe** [comment]
Having thought a bit about setting up unit testing for Alcotest, I'm not sure how best to do it. It feels wrong to test Alcotest.dev with Alcotest.dev, but I don't know of another way to do set things up in Dune. Perhaps we should use `ppx_expect` instead?

**Comment by samoht** [comment]
Not totally sure about testing -- for now, just run a few manual tests I'd say. But most importantly, do document these new features in the README and in the man pages.

**Comment by samoht** [comment]
Can you rebase this one? I'm not totally sure about the new dependency to `re` but I think it's worth it.

**Comment by CraigFe** [comment]
Rebased, and also changed the example in the README. It's now more verbose (I think it was actually so concise as to not compile before!), but demonstrates a non-trivial use of regular expressions.

Let me know what you think! :slightly_smiling_face:

**Comment by samoht** [comment]
That looks great! Thanks

**Pull request merged**
