### PR TITLE
Detect _build and move output there

### LINKED ISSUE #76: Would be nice to place output under `_build` if present
`_build` is automatically cleaned by `ocamlbuild`. If `_tests` were under `_build`, when the latter is present, there would be one less temporary directory to take care of.

### PR DESCRIPTION
**Pull request by pqwy**
Checks if there is `_build` in the current dir. Dumps outputs in `_build/_tests` if so. Fixes #76.

### CODE REVIEW

**Comment by avsm** [comment]
dislike changing the defaults on the basis of the build directory existing like this. why not explicitly specify the test output directory in the pkg.ml?

**Comment by pqwy** [comment]
Because it needs to be specified in 1-15 places per project, for every project. It's just enough noise that it's too much.

Agree with magic detection, but can we do _anything_ here not do default to `alcotest` claiming its own dir? Unconditionally go in `_build`?

**Comment by pqwy** [comment]
To clarify, the problem I have is that adding `alcotest` means that I have to tweak `.gitignore`, and I get a build-related directory that is not maintained, or cleaned, by the build system. In routine development the contents of this directory is of no interest. So I found myself constantly deleting it.

Compare `OUnit`:
```
    List.find
      dir_exists
      [
        concat pwd "_build";
        concat (dirname pwd) "_build";
        concat (dirname (dirname pwd)) "_build";
        pwd
      ]
```

**Comment by samoht** [comment]
> Unconditionally go in _build?

Yes, I think that makes sense to me. We can change the default from `_tests` to `_build/_tests`.

**Comment by pqwy** [comment]
This?

In the unlikely case that someone pulled out the test executable and deleted `_build`, or didn't use `ocamlbuild` in the first place, it dies like:

```
test.native: internal error, uncaught exception:
             Unix.Unix_error(Unix.ENOENT, "mkdir", "_build/_tests")
```

... but that's perfectly fine by me.

**Comment by pqwy** [comment]
Can I do something to help move this ahead? Add recursive dir creation if `_build` does not exist? Do something else altogether?

**Comment by samoht** [comment]
Sorry, I missed your comment. Yes, recursive `mkdir` seems a good idea to me.

**Comment by pqwy** [comment]
Ok -- mkdir is currently `Unix.mkdir`. Without extra deps, there's two ways to get a recursive one:

* call out to `mkdir -p`
* split the path on `/` and `Unix.mkdir` all prefixes.

Not sure how the first one plays with Windows, but `-p` is pretty standard in `mkdir` implementations. The second one is robust, but only if the Windows folks use forward slashes.

Any preference?

**Comment by pqwy** [comment]
Here's a recursive mkdir to recursively mkdir `_build/_tests`!

**Comment by pqwy** [comment]
@samoht ping

**Comment by samoht** [comment]
Thanks! And sorry again for the delay.

**Comment by samoht** [comment]
Released in https://github.com/ocaml/opam-repository/pull/7739

**Comment by pqwy** [comment]
Thanks!

**Pull request merged**
