### PR TITLE
Do not use symlink when writing and reading log files.

### LINKED ISSUE #272: spurious test suite failures in automated builds
The [ocaml-alcotest](https://build.opensuse.org/package/show/devel:languages:ocaml/ocaml-alcotest) runs `dune runtest --verbose --for-release-of-packages=alcotest,alcotest-lwt` after each automated rebuild.

This `dune runtest` randomly fails. Triggering a rebuild will result in a successful run.

The default output provides usually no hint what went wrong.

Examples of failure:
````
(SLE_12/ppc64le)
[   85s] Command [216] exited with code 125:
[   85s] $ (cd _build/default/test/e2e/alcotest/passing && ./quick_only_regex.exe &> _build/default/test/e2e/alcotest/passing/quick_only_regex.actual
````
````
(SLE_15/ppc64le)
[   73s] Command [255] exited with code 1:
[   73s] $ (cd _build/default && /usr/bin/diff -u test/e2e/alcotest/failing/invalid_arg_in_test.expected test/e2e/alcotest/failing/invalid_arg_in_test.processed)
[   73s] --- test/e2e/alcotest/failing/invalid_arg_in_test.expected	2020-09-01 18:07:25.760000000 +0000
[   73s] +++ test/e2e/alcotest/failing/invalid_arg_in_test.processed	2020-09-01 18:07:34.980000000 +0000
[   73s] @@ -8,7 +8,8 @@
[   73s]  ┌──────────────────────────────────────────────────────────────────────────────┐
[   73s]  │ [FAIL]        test-a          1   Failing.                                   │
[   73s]  └──────────────────────────────────────────────────────────────────────────────┘
[   73s] -[invalid] Failing test
[   73s] +ASSERT Failed
[   73s] +FAIL Failed
[   73s]  
[   73s]  Logs saved to `<build-context>/_build/_tests/<test-dir>/test-a.001.output'.
[   73s]   ──────────────────────────────────────────────────────────────────────────────
````
````
(openSUSE_Tumbleweed/aarch64)
[   96s] Command [257] exited with code 1:
[   96s] $ (cd _build/default && /usr/bin/diff -u test/e2e/alcotest/failing/long_test_case_name.expected test/e2e/alcotest/failing/long_test_case_name.processed)
[   96s] --- test/e2e/alcotest/failing/long_test_case_name.expected	2020-09-01 17:22:48.590000000 +0000
[   96s] +++ test/e2e/alcotest/failing/long_test_case_name.processed	2020-09-01 17:23:05.270000000 +0000
[   96s] @@ -7,8 +7,7 @@
[   96s]  ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
[   96s]  │ [FAIL]        test-a          1   Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse mollis, orci sed venenatis efficitur, eros est imperdiet purus, sit amet tincidunt massa diam ut elit. │
[   96s]  └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
[   96s] -ASSERT Failed
[   96s] -FAIL Failed
[   96s] +[invalid] Failing test
[   96s]  
[   96s]  Logs saved to `<build-context>/_build/_tests/<test-dir>/test-a.001.output'.
[   96s]   ──────────────────────────────────────────────────────────────────────────────
````
````
(openSUSE_Tumbleweed/i586)
[   86s] Command [215] exited with code 125:
[   86s] $ (cd _build/default/test/e2e/alcotest/passing && ./separator_testname.exe &> _build/default/test/e2e/alcotest/passing/separator_testname.actual
````
````
(openSUSE_Tumbleweed/x86_64)
[   57s] Command [259] exited with code 1:
[   57s] $ (cd _build/default && /usr/bin/diff -u test/e2e/alcotest-lwt/failing/fail_with.expected test/e2e/alcotest-lwt/failing/fail_with.processed)
[   57s] --- test/e2e/alcotest-lwt/failing/fail_with.expected	2020-09-02 18:54:28.661841455 +0000
[   57s] +++ test/e2e/alcotest-lwt/failing/fail_with.processed	2020-09-02 18:54:38.633841034 +0000
[   57s] @@ -7,7 +7,8 @@
[   57s]  ┌──────────────────────────────────────────────────────────────────────────────┐
[   57s]  │ [FAIL]        all          0   one.                                          │
[   57s]  └──────────────────────────────────────────────────────────────────────────────┘
[   57s] -[failure] should fail
[   57s] +freeing all resources
[   57s] +[failure] All is broken
[   57s]  
[   57s]  Logs saved to `<build-context>/_build/_tests/<test-dir>/all.000.output'.
[   57s]   ──────────────────────────────────────────────────────────────────────────────
````
Please let me know what additional info I shall provide.
Please let me know how future versions of alcotest can automatically provide diagnostics during `dune runtest`.

### PR DESCRIPTION
**Pull request by hhugo**
Fix #272

### CODE REVIEW

**Comment by hhugo** [comment]
Regression introduced in https://github.com/mirage/alcotest/commit/44e1f1b929e7858a4c5a7a3b2b81200c1ae58a1f

**Comment by hhugo** [comment]
gentle ping

**Comment by TheLortex** [comment]
Hi @hhugo, the PR looks sensible. Because I'm not familiar with alcotest I writing out how I think this fixes https://github.com/mirage/alcotest/issues/272

If I understand correctly, the race condition is that when two test suites with the same name are run concurrently, we get the following folders:
- `E0965BF9-...` logs for 1st run
- `6DDB68D5-...` logs for 2nd run
- `<suite_name>` symlink to either `E0965BF9-...` or `6DDB68D5-...` 

When writing to or reading from the log files, the symlink path was used, but as it is updated one of the test suites run will point to the wrong path. 


The PR fixes it by using the concrete path (using the uuid) instead for read/write operations.

**Comment by hhugo** [comment]
I've added a changelog entry and formatted the code.

**Review by TheLortex — APPROVED** [review]

**Comment by hhugo** [comment]
Thanks for merging. When should I expect a release with this change ?

**Comment by TheLortex** [comment]
The plan is to get a release soon enough, I'd like to see some of the maintenance-related PRs merged first, in particular:
- https://github.com/mirage/alcotest/pull/352
- https://github.com/mirage/alcotest/pull/351
- https://github.com/mirage/alcotest/pull/339

@CraigFe: I'm willing to take care of this if that's okay for you !

**Comment by hhugo** [comment]
https://github.com/mirage/alcotest/pull/348 would also be nice. It will likely break packages on opam and will require adding constraints.

**Pull request merged**
