### PR TITLE
Add an alcotest-lwt package

### PR DESCRIPTION
**Pull request by samoht**
See #45 for the rationals

### CODE REVIEW

**Comment by talex5** [comment]
Nice :-)

**Comment by yomimono** [comment]
This is rad, thanks for your work on it @samoht :) please @ me when you cut a release with this.

**Comment by mattjbray** [comment]
Any chance of an OPAM release for the `alcotest-lwt` package?

**Comment by samoht** [comment]
For some reasons, I completely forgot to release that package ... This is now fixed by https://github.com/ocaml/opam-repository/pull/10221

**Pull request merged**
