### PR TITLE
add boolean assert

### PR DESCRIPTION
**Pull request by zjhmale**
maybe there should be a boolean assert to check boolean values

### CODE REVIEW

**Comment by zjhmale** [comment]
@samoht

**Comment by samoht** [comment]
Thanks! There are few others combinators which might be useful here:

https://github.com/samoht/ciso/blob/master/lib_test/test_common.ml#L18-L41


I'll add them shortly.

**Comment by zjhmale** [comment]
cool!

**Comment by samoht** [comment]
alcotest 0.4.5 is now released in opam with this patch.

**Pull request merged**
