### PR TITLE
Don't show "in progress" lines when not writing to a TTY

### PR DESCRIPTION
**Pull request by CraigFe**
The Alcotest output is currently quite hard to read when printed to CI logs. For instance, in OCaml-CI:

```text
#18 3.224   ...           basic               0   Plain.
  [OK]          basic               0   Plain.
#18 3.224   ...           basic               1   Lwt.
  [OK]          basic               1   Lwt.
#18 3.224   ...           exceptions          0   Plain.
  [OK]          exceptions          0   Plain.
#18 3.224   ...           exceptions          1   Lwt toplevel.
  [OK]          exceptions          1   Lwt toplevel.
#18 3.224   ...           exceptions          2   Lwt internal.
  [OK]          exceptions          2   Lwt internal.
#18 3.224   ...           switches            0   Allocate resource.
  [OK]          switches            0   Allocate resource.
#18 3.224   ...           switches            1   Check resource deallocated.
  [OK]          switches            1   Check resource deallocated.
```

Partly this is because colours have been lost, but mostly it's due to emitting `\r` characters when not printing to a TTY. This PR disables the "..." lines when [isatty](https://man7.org/linux/man-pages/man3/isatty.3.html) returns `false`.

### CODE REVIEW

**Comment by CraigFe** [comment]
This includes a test that forces the old behaviour (`isatty.ml`), so we have some coverage over that.

**Comment by CraigFe** [comment]
Sample of the OCaml-CI output using this PR:

```
#18 5.880 Testing `LwtUtils'.
#18 5.880 This run has ID `ED20736C-C64E-4538-BA74-74F08EA66D8B'.
#18 5.880 
#18 5.880   [OK]          basic               0   Plain.
#18 5.880   [OK]          basic               1   Lwt.
#18 5.880   [OK]          exceptions          0   Plain.
#18 5.880   [OK]          exceptions          1   Lwt toplevel.
#18 5.880   [OK]          exceptions          2   Lwt internal.
#18 5.880   [OK]          switches            0   Allocate resource.
#18 5.880   [OK]          switches            1   Check resource deallocated.
#18 5.880 
#18 5.880 Full test results in `/src/_build/default/examples/lwt/_build/_tests/LwtUtils'.
#18 5.880 Test Successful in 0.000s. 7 tests run.
```

Much nicer :slightly_smiling_face:

**Comment by CraigFe** [comment]
Will merge at the end of the week, unless there are objections.

**Review by samoht — APPROVED** [review]

**Comment by CraigFe** [comment]
CI failures unrelated (and known about upstream), so merging.

**Pull request merged**
