### PR TITLE
Update to cmdliner.1.1.0

### PR DESCRIPTION
**Pull request by MisterDA**

### CODE REVIEW

**Comment by MisterDA** [comment]
I don't understand why today's setup-ocaml failed.

**Comment by TheLortex** [comment]
Hi @CraigFe and @MisterDA do you know what is the blocker for this PR ?

**Review by TheLortex — APPROVED** [review]

**Comment by TheLortex** [comment]
It's been a while since cmdliner 1.1 has been released, I think it's now good to merge !

Do you have objections @hannesm or @dinosaure  ?

**Review by dinosaure — APPROVED** [review]
LGTM, I think the only blocker was about `irmin` but the path is clear now.

**Pull request merged**
